In [1]:
import numpy as np

In [5]:
a = np.array([1,0])
b = np.array([0,1])
np.dot(a,b)

0

In [7]:
x = np.array([[1,0,1],[2,2,2]])
out=x[0:2,2]
out

array([1, 2])

In [2]:
x = np.array([[1,0],[0,1]])
y = np.array([[2,2],[2,2]])
z = np.dot(x,y)
print(z)

[[2 2]
 [2 2]]


In [8]:
import torch 

In [9]:
z = torch.tensor([[0,0,-1],[-2,0,-2],[-1,0,-1]])

In [10]:
torch.relu(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
w = torch.tensor([[[1,2,3,-4],[0.0,2.0,-3.0,0.0],[0,2,3,1],[0,0,0,0]]])

In [16]:
max_ = torch.nn.MaxPool2d(2,stride=2)
max_(w)

tensor([[[2., 3.],
         [2., 3.]]])